### ISSUE TITLE
Features wrongly aligned

### ISSUE THREAD

**Issue by TropicSapling** [NN-Dev-Team/Nordic-Network#89]

**Comment by TropicSapling** [comment]
Confirmed on all devices, also found the problem so fixing very soon :)

**Comment by TropicSapling** [comment]
Fixed in https://github.com/TropicSapling/Nordic-Network/commit/2ef1b88c06d1fdf9cca6474c12a6585215903cfd

**Comment by saskakol** [comment]
Feature boxes are still broken on mobile.
Suggested fix: Use Bootstrap Panels as a base, and style on top of that. This will make the boxes responsive by default, and custom styles can still be applied.

Moved from completed to in progress.

**Comment by TropicSapling** [comment]
@iSasFTW I think I didn't do that because I didn't know how to customise it? Can't remember though

**Comment by saskakol** [comment]
@TropicSapling You can pretty much style it whatever way you want, and it should override the bootstrap CSS.

**Comment by TropicSapling** [comment]
@iSasFTW I don't think so, I think you would have to use `!important` for it to override :/

**Comment by saskakol** [comment]
@tropicsapling I've overridden Bootstrap before without using !important (buttons in that case), but it would work with the flag too.

**Comment by TropicSapling** [comment]
@iSasFTW Hmm ok I'll try again and see if it works :)

**Comment by TropicSapling** [comment]
Fixed in https://github.com/NN-Dev-Team/Nordic-Network/pull/282
